spring:
    datasource:
        url: jdbc:h2:mem:testdb  # Base de données en mémoire (modifiable si besoin)
        driver-class-name: org.h2.Driver
        username: sa
        password:  # Aucun mot de passe par défaut

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: update  # Permet d'automatiser la création des tables
        show-sql: true  # Pour voir les requêtes SQL dans la console

    h2:
        console:
            enabled: true  # Active la console H2 pour visualiser les données
            path: /h2-console  # URL d'accès : http://localhost:8080/h2-console

server:
    port: 8080  # Port de l'application Spring Boot